apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: blue-green
  labels:
    app: myapp
spec:
  type: NodePort
  selector:
    app: myapp
    color: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
  sessionAffinity: None
